---
mode: parallel

blueprint:
  name: Frigate / Reolink Notifications
  domain: automation

  input:
    trigger_sensor:
      name: Trigger
      description: Sensor that triggers the notification (doorbell, Frigate occupancy, etc).
      selector:
        entity:
          filter:
            - integration: frigate
              domain: binary_sensor
              device_class: occupancy
            - integration: reolink
              domain: binary_sensor

    media_entity:
      name: Image
      description: Camera or image entity to snapshot and use as the notification image.
      selector:
        entity:
          filter:
            - integration: reolink
              domain:
                - camera
                - image
            - integration: frigate
              domain:
                - camera
                - image

    notification_message:
      name: Message
      description: The main text of the notification. Required.
      selector:
        text:
          multiline: true

    notification_title:
      name: Title
      description: Optional title for the notification.
      default: ""
      selector:
        text:

    notification_icon:
      name: Icon
      description: Android notification icon.
      default: mdi:cctv
      selector:
        icon:

    notification_color:
      name: Color
      default: "#0000ff"
      description: Android notification icon color.
      selector:
        text:
          type: color

    notification_group:
      name: Group
      description: https://companion.home-assistant.io/docs/notifications/notifications-basic/#grouping
      default: ""
      selector:
        text:

    notification_channel:
      name: Channel
      description: https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-channels
      default: Camera Detection
      selector:
        text:

    notification_visibility:
      name: Visibility
      description: https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-visibility
      default: public
      selector:
        select:
          mode: dropdown
          options:
            - public
            - private
            - secret

    notification_vibration_pattern:
      name: Vibration pattern
      description: https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-vibration-pattern
      default: "100, 1000, 100, 1000, 100, 1000"
      selector:
        text:

    notification_click_action:
      name: Click action
      description: https://companion.home-assistant.io/docs/notifications/notifications-basic/#opening-a-url
      default: ""
      selector:
        text:
          type: url

    notification_rate_limit:
      name: Rate limit
      description: Minimum time between notifications. Activity within this time will not trigger a new notification.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: seconds
          mode: box

    notification_delay:
      name: Delay
      description: How long to wait to send a notification after taking a snapshot.
      default: "00:00:00"
      selector:
        duration:

trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: "on"

variables:
  timestamp: "{{ now().strftime('%Y%m%d_%H%M%S') }}"
  media_entity: !input media_entity
  media_domain: "{{ media_entity.split('.')[0] }}"
  snapshot_file_name: "{{ trigger.entity_id.split('.')[1] }}_{{ timestamp }}.jpg"
  snapshot_path: "/config/www/snapshots/{{ snapshot_file_name }}"
  snapshot_url: "/local/snapshots/{{ snapshot_file_name }}"
  notification_rate_limit: !input notification_rate_limit

condition:
  - condition: template
    value_template: >-
      {% set last = this.attributes.last_triggered %}
      {% set limit = notification_rate_limit %}
      {{ last is none or (as_timestamp(now()) - as_timestamp(last)) > limit }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ media_domain == 'camera' }}"
        sequence:
          - service: camera.snapshot
            target:
              entity_id: !input media_entity
            data:
              filename: "{{ snapshot_path }}"

      - conditions:
          - condition: template
            value_template: "{{ media_domain == 'image' }}"
        sequence:
          - service: image.snapshot
            target:
              entity_id: !input media_entity
            data:
              filename: "{{ snapshot_path }}"

  - delay: !input notification_delay

  - service: notify.all_devices
    data:
      message: !input notification_message
      title: !input notification_title
      data:
        image: "{{ snapshot_url }}"
        notification_icon: !input notification_icon
        group: !input notification_group
        channel: !input notification_channel
        vibrationPattern: !input notification_vibration_pattern
        importance: high
        priority: high
        visibility: !input notification_visibility
        color: !input notification_color
        ttl: 0
        clickAction: !input notification_click_action
